[colors]
background = '#1717178e'
black = '#171717'
blue = '#523792'
cursor = '#3c3c3d'
cyan = '#64589A'
foreground = '#3c3c3d'
green = '#524CB8'
magenta = '#906B9E'
red = '#A667D3'
tabs = '#3c3c3d'
tabs-active = '#6C9AC0'
white = '#3c3c3d'
yellow = '#79797a'
dim-black = '#1717178e'
dim-blue = '#5237928e'
dim-cyan = '#64589A8e'
dim-foreground = '#3c3c3d8e'
dim-green = '#524CB88e'
dim-magenta = '#906B9E8e'
dim-red = '#A667D38e'
dim-white = '#6C9AC08e'
dim-yellow = '#79797a8e'
light-black = '#7d69ad'
light-blue = '#8a81b3'
light-cyan = '#7d78c9'
light-foreground = '#ab90b6'
light-green = '#bc8dde'
light-magenta = '#90b3cf'
light-red = '#3c3c3d'
light-white = '#7d69ad'
light-yellow = '#8a81b3'
