[colors.primary]
background = "#171717"
foreground = "#c4c4c3"

[colors.cursor]
text = "#171717"
cursor = "#c4c4c3"

[colors.vi_mode_cursor]
text = "#171717"
cursor = "#c4c4c3"

[colors.search.matches]
foreground = "#171717"
background = "#c4c4c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6e675a"
background = "#99948e"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#171717"
red = "#A2633F"
green = "#5B843D"
yellow = "#68934D"
blue = "#91AA5F"
magenta = "#B9A64D"
cyan = "#794B89"
white = "#99948e"

[colors.bright]
black = "#6e675a"
red = "#be8869"
green = "#81b757"
yellow = "#88be68"
blue = "#aec77e"
magenta = "#c6b97c"
cyan = "#a462bb"
white = "#c4c4c3"

[colors.dim]
black = "#c4c4c3"
red = "#be8869"
green = "#c6b97c"
yellow = "#88be68"
blue = "#aec77e"
magenta = "#81b757"
cyan = "#a462bb"
white = "#6e675a"

