[colors]
background = '#1717178e'
black = '#171717'
blue = '#A3493F'
cursor = '#3c3c3c'
cyan = '#48A34E'
foreground = '#3c3c3c'
green = '#C09D50'
magenta = '#232299'
red = '#4446BB'
tabs = '#3c3c3c'
tabs-active = '#B756AD'
white = '#3c3c3c'
yellow = '#797979'
dim-black = '#1717178e'
dim-blue = '#A3493F8e'
dim-cyan = '#48A34E8e'
dim-foreground = '#3c3c3c8e'
dim-green = '#C09D508e'
dim-magenta = '#2322998e'
dim-red = '#4446BB8e'
dim-white = '#B756AD8e'
dim-yellow = '#7979798e'
light-black = '#ba766f'
light-blue = '#75ba7a'
light-cyan = '#cfb57b'
light-foreground = '#5a59b2'
light-green = '#7274cc'
light-magenta = '#c980c1'
light-red = '#3c3c3c'
light-white = '#ba766f'
light-yellow = '#75ba7a'
