[colors.primary]
background = "#171717"
foreground = "#3c3c3c"

[colors.cursor]
text = "#171717"
cursor = "#3c3c3c"

[colors.vi_mode_cursor]
text = "#171717"
cursor = "#3c3c3c"

[colors.search.matches]
foreground = "#171717"
background = "#3c3c3c"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#b6b6b6"
background = "#797979"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#171717"
red = "#A3493F"
green = "#48A34E"
yellow = "#C09D50"
blue = "#232299"
magenta = "#4446BB"
cyan = "#B756AD"
white = "#797979"

[colors.bright]
black = "#b6b6b6"
red = "#ba766f"
green = "#75ba7a"
yellow = "#cfb57b"
blue = "#5a59b2"
magenta = "#7274cc"
cyan = "#c980c1"
white = "#3c3c3c"

[colors.dim]
black = "#3c3c3c"
red = "#ba766f"
green = "#7274cc"
yellow = "#cfb57b"
blue = "#5a59b2"
magenta = "#75ba7a"
cyan = "#c980c1"
white = "#b6b6b6"

