[colors]
background = '#1717178e'
black = '#171717'
blue = '#A2633F'
cursor = '#c4c4c3'
cyan = '#5B843D'
foreground = '#c4c4c3'
green = '#68934D'
magenta = '#91AA5F'
red = '#B9A64D'
tabs = '#c4c4c3'
tabs-active = '#794B89'
white = '#c4c4c3'
yellow = '#99948e'
dim-black = '#1717178e'
dim-blue = '#A2633F8e'
dim-cyan = '#5B843D8e'
dim-foreground = '#c4c4c38e'
dim-green = '#68934D8e'
dim-magenta = '#91AA5F8e'
dim-red = '#B9A64D8e'
dim-white = '#794B898e'
dim-yellow = '#99948e8e'
light-black = '#be8869'
light-blue = '#81b757'
light-cyan = '#88be68'
light-foreground = '#aec77e'
light-green = '#c6b97c'
light-magenta = '#a462bb'
light-red = '#c4c4c3'
light-white = '#be8869'
light-yellow = '#81b757'
